In [64]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [65]:
df = pd.read_csv(r"C:\Users\saile\OneDrive\Desktop\research\data\sales_train_validation.csv")
df.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4

### 1. state_id = ca 2.store_id = ca_1 3. d_1-d_1913 check for sales =!0

In [66]:
cleaned = df[df['store_id'].isin(['CA_1', 'CA_2', 'CA_3'])]

In [67]:
d_cols = [c for c in cleaned.columns if c.startswith('d_')]

In [68]:
cleaned['zero_pct'] = (cleaned[d_cols] == 0).mean(axis=1) * 100
top_10_rows = cleaned.nsmallest(12, 'zero_pct')

C:\Users\saile\AppData\Local\Temp\ipykernel_7064\3522298377.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cleaned['zero_pct'] = (cleaned[d_cols] == 0).mean(axis=1) * 100

In [69]:
top_10_rows

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913,zero_pct
5859,FOODS_3_586_CA_2_validation,FOODS_3_586,FOODS_3,FOODS,CA_2,CA,34,25,16,25,...,47,39,26,45,42,30,34,39,36,0.156822
8877,FOODS_3_555_CA_3_validation,FOODS_3_555,FOODS_3,FOODS,CA_3,CA,18,38,14,22,...,46,49,31,31,27,26,30,33,36,0.209096
5353,FOODS_3_080_CA_2_validation,FOODS_3_080,FOODS_3,FOODS,CA_2,CA,21,15,9,10,...,14,18,13,11,10,16,13,16,20,0.261370
8402,FOODS_3_080_CA_3_validation,FOODS_3_080,FOODS_3,FOODS,CA_3,CA,28,17,24,18,...,22,15,17,7,11,15,15,21,13,0.261370
8711,FOODS_3_389_CA_3_validation,FOODS_3_389,FOODS_3,FOODS,CA_3,CA,15,24,11,19,...,27,28,19,17,18,17,16,19,20,0.261370
8908,FOODS_3_586_CA_3_validation,FOODS_3_586,FOODS_3,FOODS,CA_3,CA,56,55,45,57,...,85,91,77,75,70,48,61,74,78,0.261370
2304,FOODS_3_080_CA_1_validation,FOODS_3_080,FOODS_3,FOODS,CA_1,CA,33,16,16,14,...,23,23,15,12,30,13,10,25,25,0.313643
2476,FOODS_3_252_CA_1_validation,FOODS_3_252,FOODS_3,FOODS,CA_1,CA,19,14,10,8,...,57,49,21,46,24,35,33,49,52,0.313643
2779,FOODS_3_555_CA_1_validation,FOODS_3_555,FOODS_3,FOODS,CA_1,CA,23,16,14,10,...,32,26,13,21,15,14,14,23,24,0.313643
8550,FOODS_3_228_CA_3_validation,FOODS_3_228,FOODS_3,FOODS,CA_3,CA,19,10,9,5,...,9,9,4,7,8,1,5,6,11,0.313643
8574,FOODS_3_252_CA_3_validation,FOODS_3_252,FOODS_3,FOODS,CA_3,CA,39,38,18,37,...,65,81,59,56,29,46,35,61,39,0.313643
9016,FOODS_3_694_CA_3_validation,FOODS_3_694,FOODS_3,FOODS,CA_3,CA,26,16,18,11,...,16,20,17,20,16,19,22,24,24,0.313643

In [70]:
top_10_rows.reset_index(drop=True, inplace = True)
top_10_rows

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913,zero_pct
0,FOODS_3_586_CA_2_validation,FOODS_3_586,FOODS_3,FOODS,CA_2,CA,34,25,16,25,...,47,39,26,45,42,30,34,39,36,0.156822
1,FOODS_3_555_CA_3_validation,FOODS_3_555,FOODS_3,FOODS,CA_3,CA,18,38,14,22,...,46,49,31,31,27,26,30,33,36,0.209096
2,FOODS_3_080_CA_2_validation,FOODS_3_080,FOODS_3,FOODS,CA_2,CA,21,15,9,10,...,14,18,13,11,10,16,13,16,20,0.261370
3,FOODS_3_080_CA_3_validation,FOODS_3_080,FOODS_3,FOODS,CA_3,CA,28,17,24,18,...,22,15,17,7,11,15,15,21,13,0.261370
4,FOODS_3_389_CA_3_validation,FOODS_3_389,FOODS_3,FOODS,CA_3,CA,15,24,11,19,...,27,28,19,17,18,17,16,19,20,0.261370
5,FOODS_3_586_CA_3_validation,FOODS_3_586,FOODS_3,FOODS,CA_3,CA,56,55,45,57,...,85,91,77,75,70,48,61,74,78,0.261370
6,FOODS_3_080_CA_1_validation,FOODS_3_080,FOODS_3,FOODS,CA_1,CA,33,16,16,14,...,23,23,15,12,30,13,10,25,25,0.313643
7,FOODS_3_252_CA_1_validation,FOODS_3_252,FOODS_3,FOODS,CA_1,CA,19,14,10,8,...,57,49,21,46,24,35,33,49,52,0.313643
8,FOODS_3_555_CA_1_validation,FOODS_3_555,FOODS_3,FOODS,CA_1,CA,23,16,14,10,...,32,26,13,21,15,14,14,23,24,0.313643
9,FOODS_3_228_CA_3_validation,FOODS_3_228,FOODS_3,FOODS,CA_3,CA,19,10,9,5,...,9,9,4,7,8,1,5,6,11,0.313643
10,FOODS_3_252_CA_3_validation,FOODS_3_252,FOODS_3,FOODS,CA_3,CA,39,38,18,37,...,65,81,59,56,29,46,35,61,39,0.313643
11,FOODS_3_694_CA_3_validation,FOODS_3_694,FOODS_3,FOODS,CA_3,CA,26,16,18,11,...,16,20,17,20,16,19,22,24,24,0.313643

In [71]:
top_10_rows = top_10_rows.drop(columns=['id', 'dept_id', 'cat_id'])

In [72]:
top_10_rows

,item_id,store_id,state_id,d_1,d_2,d_3,d_4,d_5,d_6,d_7,...,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913,zero_pct
0,FOODS_3_586,CA_2,CA,34,25,16,25,37,20,32,...,47,39,26,45,42,30,34,39,36,0.156822
1,FOODS_3_555,CA_3,CA,18,38,14,22,31,35,22,...,46,49,31,31,27,26,30,33,36,0.209096
2,FOODS_3_080,CA_2,CA,21,15,9,10,17,14,29,...,14,18,13,11,10,16,13,16,20,0.261370
3,FOODS_3_080,CA_3,CA,28,17,24,18,28,32,25,...,22,15,17,7,11,15,15,21,13,0.261370
4,FOODS_3_389,CA_3,CA,15,24,11,19,18,19,18,...,27,28,19,17,18,17,16,19,20,0.261370
5,FOODS_3_586,CA_3,CA,56,55,45,57,54,67,46,...,85,91,77,75,70,48,61,74,78,0.261370
6,FOODS_3_080,CA_1,CA,33,16,16,14,20,23,24,...,23,23,15,12,30,13,10,25,25,0.313643
7,FOODS_3_252,CA_1,CA,19,14,10,8,8,13,16,...,57,49,21,46,24,35,33,49,52,0.313643
8,FOODS_3_555,CA_1,CA,23,16,14,10,17,21,9,...,32,26,13,21,15,14,14,23,24,0.313643
9,FOODS_3_228,CA_3,CA,19,10,9,5,7,5,5,...,9,9,4,7,8,1,5,6,11,0.313643
10,FOODS_3_252,CA_3,CA,39,38,18,37,40,46,27,...,65,81,59,56,29,46,35,61,39,0.313643
11,FOODS_3_694,CA_3,CA,26,16,18,11,10,16,20,...,16,20,17,20,16,19,22,24,24,0.313643

In [73]:
# All day columns
d_cols = [c for c in top_10_rows.columns if c.startswith("d_")]

In [74]:
long_df = top_10_rows.melt(
    id_vars=["item_id", "store_id"],
    value_vars=d_cols,
    var_name="day",
    value_name="sales"
)

In [75]:
calendar_df = pd.read_csv(r"C:\Users\saile\OneDrive\Desktop\research\data\calendar.csv")

In [76]:
sellprice_df = pd.read_csv(r"C:\Users\saile\OneDrive\Desktop\research\data\sell_prices.csv")
sellprice_df

        store_id        item_id  wm_yr_wk  sell_price
0           CA_1  HOBBIES_1_001     11325        9.58
1           CA_1  HOBBIES_1_001     11326        9.58
2           CA_1  HOBBIES_1_001     11327        8.26
3           CA_1  HOBBIES_1_001     11328        8.26
4           CA_1  HOBBIES_1_001     11329        8.26
...          ...            ...       ...         ...
6841116     WI_3    FOODS_3_827     11617        1.00
6841117     WI_3    FOODS_3_827     11618        1.00
6841118     WI_3    FOODS_3_827     11619        1.00
6841119     WI_3    FOODS_3_827     11620        1.00
6841120     WI_3    FOODS_3_827     11621        1.00

[6841121 rows x 4 columns]

In [77]:
calendar_df = pd.read_csv(r"C:\Users\saile\OneDrive\Desktop\research\data\calendar.csv")
final_df = long_df.merge(calendar_df, left_on="day", right_on="d", how="left").drop(columns=["d"])

final_df

,item_id,store_id,day,sales,date,wm_yr_wk,weekday,wday,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,FOODS_3_586,CA_2,d_1,34,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0
1,FOODS_3_555,CA_3,d_1,18,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0
2,FOODS_3_080,CA_2,d_1,21,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0
3,FOODS_3_080,CA_3,d_1,28,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0
4,FOODS_3_389,CA_3,d_1,15,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22951,FOODS_3_252,CA_1,d_1913,52,2016-04-24,11613,Sunday,2,4,2016,NaN,NaN,NaN,NaN,0,0,0
22952,FOODS_3_555,CA_1,d_1913,24,2016-04-24,11613,Sunday,2,4,2016,NaN,NaN,NaN,NaN,0,0,0
22953,FOODS_3_228,CA_3,d_1913,11,2016-04-24,11613,Sunday,2,4,2016,NaN,NaN,NaN,NaN,0,0,0
22954,FOODS_3_252,CA_3,d_1913,39,2016-04-24,11613,Sunday,2,4,2016,NaN,NaN,NaN,NaN,0,0,0
22955,FOODS_3_694,CA_3,d_1913,24,2016-04-24,11613,Sunday,2,4,2016,NaN,NaN,NaN,NaN,0,0,0

In [78]:
final = final_df.merge(
    sellprice_df,
    on=["item_id", "store_id", "wm_yr_wk"],
    how="left"
)

In [79]:
final

,item_id,store_id,day,sales,date,wm_yr_wk,weekday,wday,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price
0,FOODS_3_586,CA_2,d_1,34,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0,1.48
1,FOODS_3_555,CA_3,d_1,18,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0,1.48
2,FOODS_3_080,CA_2,d_1,21,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0,1.48
3,FOODS_3_080,CA_3,d_1,28,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0,1.48
4,FOODS_3_389,CA_3,d_1,15,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0,1.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22951,FOODS_3_252,CA_1,d_1913,52,2016-04-24,11613,Sunday,2,4,2016,NaN,NaN,NaN,NaN,0,0,0,1.58
22952,FOODS_3_555,CA_1,d_1913,24,2016-04-24,11613,Sunday,2,4,2016,NaN,NaN,NaN,NaN,0,0,0,1.68
22953,FOODS_3_228,CA_3,d_1913,11,2016-04-24,11613,Sunday,2,4,2016,NaN,NaN,NaN,NaN,0,0,0,1.68
22954,FOODS_3_252,CA_3,d_1913,39,2016-04-24,11613,Sunday,2,4,2016,NaN,NaN,NaN,NaN,0,0,0,1.58
22955,FOODS_3_694,CA_3,d_1913,24,2016-04-24,11613,Sunday,2,4,2016,NaN,NaN,NaN,NaN,0,0,0,1.68

In [ ]:
final = final.drop(columns=['day', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'snap_TX', 'snap_WI'], errors='ignore')

SyntaxError: invalid syntax (1040477130.py, line 1)

In [80]:
final.to_csv(r"C:\Users\saile\OneDrive\Desktop\research\data\final_cleaned.csv", index=False)
print("Saved to data/final_cleaned.csv")

Saved to data/final_cleaned.csv